/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Avatar.def
	public class EntityBaseEntityCall_AvatarBase : EntityCall
	{

		public EntityBaseEntityCall_AvatarBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

	}

	public class EntityCellEntityCall_AvatarBase : EntityCall
	{

		public EntityCellEntityCall_AvatarBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void reqDirection(UInt64 arg1, Vector3 arg2)
		{
			Bundle pBundle = newCall("reqDirection", 0);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			bundle.writeVector3(arg2);
			sendCall(null);
		}

		public void reqPosition(UInt64 arg1, Vector3 arg2)
		{
			Bundle pBundle = newCall("reqPosition", 0);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			bundle.writeVector3(arg2);
			sendCall(null);
		}

	}
	}
